//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Descargar
    {
        public System.Guid ID { get; set; }
        public System.Guid IDUsuarioDescargo { get; set; }
        public System.DateTime FechaDescarga { get; set; }
        public System.Guid IDCurso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
