//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Usuarios
    {
        public System.Guid ID { get; set; }
        public System.Guid IDUsuario { get; set; }
        public System.Guid IDRole { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
